payload:
  - PROCESS-NAME,v2ray
  - PROCESS-NAME,xray
  - PROCESS-NAME,naive
  - PROCESS-NAME,trojan
  - PROCESS-NAME,trojan-go
  - PROCESS-NAME,ss-local
  - PROCESS-NAME,privoxy
  - PROCESS-NAME,leaf
  - PROCESS-NAME,v2ray.exe
  - PROCESS-NAME,xray.exe
  - PROCESS-NAME,naive.exe
  - PROCESS-NAME,trojan.exe
  - PROCESS-NAME,trojan-go.exe
  - PROCESS-NAME,ss-local.exe
  - PROCESS-NAME,privoxy.exe
  - PROCESS-NAME,leaf.exe
  - PROCESS-NAME,Surge
  - PROCESS-NAME,Surge 2
  - PROCESS-NAME,Surge 3
  - PROCESS-NAME,Surge 4
  - PROCESS-NAME,Surge%202
  - PROCESS-NAME,Surge%203
  - PROCESS-NAME,Surge%204
  - PROCESS-NAME,Thunder
  - PROCESS-NAME,DownloadService
  - PROCESS-NAME,qBittorrent
  - PROCESS-NAME,Transmission
  - PROCESS-NAME,fdm
  - PROCESS-NAME,aria2c
  - PROCESS-NAME,Folx
  - PROCESS-NAME,NetTransport
  - PROCESS-NAME,uTorrent
  - PROCESS-NAME,WebTorrent
  - PROCESS-NAME,aria2c.exe
  - PROCESS-NAME,BitComet.exe
  - PROCESS-NAME,fdm.exe
  - PROCESS-NAME,NetTransport.exe
  - PROCESS-NAME,qbittorrent.exe
  - PROCESS-NAME,Thunder.exe
  - PROCESS-NAME,ThunderVIP.exe
  - PROCESS-NAME,transmission-daemon.exe
  - PROCESS-NAME,transmission-qt.exe
  - PROCESS-NAME,uTorrent.exe
  - PROCESS-NAME,WebTorrent
  - PROCESS-NAME,Starter
  - PROCESS-NAME,WinClient
  - PROCESS-NAME,Starter_updated
  - PROCESS-NAME,ffprobe
  - PROCESS-NAME,ffplay
  - PROCESS-NAME,ffmpeg
  - PROCESS-NAME,CefSharp.BrowserSubprocess
  - PROCESS-NAME,uTools
  - PROCESS-NAME,IDMan
  - PROCESS-NAME,IDMGrHlp
  - PROCESS-NAME,IEMonitor
  - PROCESS-NAME,Binance
  - PROCESS-NAME,nircmd
  - PROCESS-NAME,elevate
  - PROCESS-NAME,OUTLOOK
  - PROCESS-NAME,EXCEL
  - PROCESS-NAME,GROOVE
  - PROCESS-NAME,excelcnv
  - PROCESS-NAME,ACCICONS
  - PROCESS-NAME,MSACCESS
  - PROCESS-NAME,officeappguardwin32
  - PROCESS-NAME,ONENOTE
  - PROCESS-NAME,ONENOTEM
  - PROCESS-NAME,SETLANG
  - PROCESS-NAME,WINWORD
  - PROCESS-NAME,WORDICON
  - PROCESS-NAME,Wordconv
  - PROCESS-NAME,XLICONS
  - PROCESS-NAME,OneDrive
  - PROCESS-NAME,WinStore.App
  - PROCESS-NAME,RuntimeBroker
  
